version: "3"
services:
  website:
    image: nginix
    ports:
      - "8080:80"
    restart: always
  website2: 
    image: nginix
    ports: 
      - :"8081:80"
    restartr: always
    networks:
    coffee:
      ipv4_address: 192.168.92.21
networks:
  coffee:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"